config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :new, :show] do
    # resouces :subs, only: [:index]
  end

  resource :session, only: [:create, :new, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subs, except: [:destroy] do
    resources :posts, only: [:index]
  end

  resources :posts, except: [:index] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :new]
  end

  resources :comments, only: [:show] do
    resources :comments, only: :create
    resources :votes, only: [:create]
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  has_many :votes, as: :votable

  def vote_count
    self.votes.pluck(:value).reduce(1) do |acc, value|
      acc += value
    end
  end

  belongs_to :author,
    foreign_key: :author_id,
    class_name: 'User'

  belongs_to :parent_comment,
    class_name: 'Comment',
    optional: true

  belongs_to :post

  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: 'Comment'


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_current_user

  def show
    @comment = Comment.find_by(id: params[:id])

  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if params[:post_id]
      @comment.post_id = params[:post_id]
    else
      @comment.parent_comment_id = params[:comment_id]
      @comment.post_id = @comment.parent_comment.post_id
    end

    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      if @comment.parent_comment
        flash[:errors] = @comment.errors.full_messages
        redirect_to comment_url(@comment.parent_comment)
      else
        flash.now[:errors] = @comment.errors.full_messages
        render :new
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= link_to comment.content, comment_url(comment) %>

<ul>
  <% all_comments[comment.id].each do |comment2| %>

    <li>
      <%= render 'comments/comment', comment: comment2, all_comments: all_comments %>
    </li>

  <% end %>
</ul>

app/views/comments/new.html.erb
Add Comment
<% if flash[:errors] %>
<% flash[:errors].each do |error| %>
<%= error %>
<% end %>
<% end %>
<form class="" action="<%= params[:post_id] ? post_comments_url(params[:post_id]) : comment_comments_url(params[:comment_id]) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Comment
  <br>

  <textarea name="comment[content]" rows="8" cols="40"><%= @comment.content %></textarea>
  <br>

  <input type="submit" name="" value="Add Comment">
</form>

app/views/comments/show.html.erb
(<%= @comment.vote_count %>)<%= @comment.content %>

<%= link_to "Post", post_url(@comment.post_id) %>

<br>
<form class="" action="<%= comment_votes_url(@comment) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="vote[value]" value="1">
  <input type="submit" name="" value="Upvote">
</form>

<form class="" action="<%= comment_votes_url(@comment) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="vote[value]" value="-1">
  <input type="submit" name="" value="Downvote">
</form>
<br>
Reply to this comment:

<form class="" action="<%= comment_comments_url(@comment) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Comment
  <br>

  <textarea name="comment[content]" rows="8" cols="40"></textarea>
  <br>

  <input type="submit" name="" value="Reply Comment">
</form>

<ul>
  <% all_comments = @comment.post.comments_by_parent_id %>
  <% all_comments[@comment.id].each do |comment| %>
  <li>
    <%= render 'comments/comment', comment: comment, all_comments: all_comments %>
  </li>
  <% end %>
</ul>