config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :new, :show] do
    # resouces :subs, only: [:index]
  end

  resource :session, only: [:create, :new, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subs, except: [:destroy] do
    resources :posts, only: [:index]
  end

  resources :posts, except: [:index] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :new]
  end

  resources :comments, only: [:show] do
    resources :comments, only: :create
    resources :votes, only: [:create]
  end

end

app/models/sub.rb
class Sub < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :moderator, :title, :description, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: 'User'

  has_many :postings

  has_many :posts,
    through: :postings
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_current_user, only: [:new, :edit, :create, :update]

  def new
    @sub = Sub.new

  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.friendly.find(params[:id])
  end

  def update
    @sub = Sub.friendly.find(params[:id])
    if is_moderator(@sub)
      if @sub.update(sub_params)
        redirect_to sub_url(@sub)
      else
        flash.now[:errors] = @sub.errors.full_messages
        render :edit
      end
    else
      flash[:notice] = ["You are not authorized to do that"]
      redirect_to sub_url(@sub)
    end

  end

  def show
    @sub = Sub.friendly.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

  private

  def is_moderator?(sub)

    if sub.moderator_id == current_user.id
      true
    else
      false
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/index.html.erb
<% @subs.each do |sub| %>
  <li>
    <%= link_to sub.title, sub_url(sub) %>
  </li>
<% end %>

<br>
<br>
<br>
<br>

<div class="link">
<%= link_to "Create Sub", new_sub_url %>
</div>

app/views/subs/new.html.erb
New Sub
<form class="" action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Title <input id="Title" type="text" name="sub[title]" value="<%= @sub.title %>">
  <br>
  Description
  <br>
  <textarea name="sub[description]" rows="8" cols="40"><%= @sub.description %></textarea>
  <br>
  <input type="submit" name="" value="Add New Sub">


</form>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h2>Description</h2>
<p>
  <%= @sub.description %>
</p>

<div class="link">
  <%= link_to "Make New Post!", new_post_url %>
</div>


<%= render 'posts/index', sub: @sub %>

<div class="link">
  <%= link_to 'All Subs', subs_url %>
</div>