config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :new, :show] do
    # resouces :subs, only: [:index]
  end

  resource :session, only: [:create, :new, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subs, except: [:destroy] do
    resources :posts, only: [:index]
  end

  resources :posts, except: [:index] do
    resources :votes, only: [:create]
    resources :comments, only: [:create, :new]
  end

  resources :comments, only: [:show] do
    resources :comments, only: :create
    resources :votes, only: [:create]
  end

end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  validates :title, presence: true

  has_many :votes, as: :votable

  def vote_count
    self.votes.pluck(:value).reduce(1) do |acc, value|
      acc += value
    end
  end

  has_many :postings

  has_many :subs,
    through: :postings

  belongs_to :author,
    foreign_key: :author_id,
    class_name: 'User'

  has_many :comments

  def top_level_comments
    self.comments.where(parent_comment_id: nil).include(:child_comments)
  end

  def comments_by_parent_id
    result = Hash.new {[]}
    comments = self.comments.includes(:author)

    comments.each do |comment|


      result[comment.parent_comment_id] += [comment]

    end
    result
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_current_user, except:[:show, :index]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def index
    @posts = Sub.find_by(id: params[:sub_id]).posts
  end

  def show
    @post = Post.friendly.find(params[:id])
    @comment = Comment.new
    @all_comments = @post.comments_by_parent_id
  end

  def edit
    @post = Post.friendly.find(params[:id])

  end

  def update
    @post = Post.friendly.find(params[:id])

    if is_author?
      if @post.update(post_params)
        redirect_to post_url(@post)
      else
        flash.now[:errors] = @post.errors.full_messages
        render :edit
      end

    else
      flash[:notice] = ["You are not authorized to do that"]
      redirect_to post_url(@post)
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def is_author?
    current_user.id == @post.author_id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<ul>

<% sub.posts.each do |post| %>
  <li>
    <%= link_to post.title, post_url(post) %>
  </li>

<% end %>

</ul>

app/views/posts/_really_cool_partial.html.erb
<% if @post.top_level_comments %>
  <ul>

  <% @post.top_level_comments.each do |comment| %>
    <li>
      <%= render 'comments/comment', comment: comment %>
    </li>
  <% end %>
  <br>

  </ul>
<% end %>

app/views/posts/edit.html.erb
Edit Post
<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Title <input id="Title" type="text" name="post[title]" value="<%= @post.title %>">
  <br>
  URL <input id="URL" type="text" name="post[url]" value="<%= @post.url %>">
  Content
  <br>
  <textarea name="post[content]" rows="8" cols="40"><%= @post.content %></textarea>
  <br>
  <input type="submit" name="" value="Update Post">
  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <input
      type="checkbox"
      name="post[sub_ids][]"
      value="<%=sub.id%>"
      <%= "checked" if @post.sub_ids.include?(sub.id) %>
    >
    <%= sub.title %>
  <% end %>


</form>

app/views/posts/new.html.erb
New Post
<form class="" action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  Title <input id="Title" type="text" name="post[title]" value="<%= @post.title %>">
  <br>
  URL <input id="URL" type="text" name="post[url]" value="<%= @post.url %>">
  Content
  <br>
  <textarea name="post[content]" rows="8" cols="40"><%= @post.content %></textarea>
  <br>
  <input type="submit" name="" value="Add New Post">
  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <input
      type="checkbox"
      name="post[sub_ids][]"
      value="<%=sub.id%>"
      <%= "checked" if @post.sub_ids.include?(sub.id) %>
    >
    <%= sub.title %>
  <% end %>


</form>

app/views/posts/show.html.erb
<h1>
(<%= @post.vote_count %>)
<%= link_to @post.title, post_url(@post) %>
By <%= @post.author.username %>
</h1>

Content:
<%= @post.content %>

<form class="" action="<%= post_votes_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="vote[value]" value="1">
  <input type="submit" name="" value="Upvote">
</form>

<form class="" action="<%= post_votes_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="vote[value]" value="-1">
  <input type="submit" name="" value="Downvote">
</form>

<%#= button_to 'Upvote', post_votes_url(@post), method: :post %>
<%#= button_to 'Downvote', post_votes_url(@post), method: :post %>

<ul>
<% @post.subs.each do |sub| %>
  <li> <%= link_to sub.title, sub_url(sub) %> </li>
<% end %>
</ul>

<div class="link">

<%= link_to "Edit Post", edit_post_url(@post) %>

<%= link_to "Add Comment", new_post_comment_url(@post) %>

</div>

<div class="comments">

Comments
<br>

<% @all_comments[nil].each do |comment| %>
  <li>
    <%= render 'comments/comment', comment: comment, all_comments: @all_comments %>
  </li>
<% end %>

</div>

<div class="link">
  <%= link_to "All Sub", subs_url %>
</div>